package com.example.vidyavahini

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val appName: String,
    val studentCommuteBuddy: String,
    val selectYourRoute: String,
    val enterMobile: String,
    val sendOtp: String,
    val verifyOtp: String,
    val pingButton: String,
    val safeReach: String,
    val reportBreakdown: String,
    val livePosition: String,
    val minutesToStop: String,
    val settings: String,
    val profile: String,
    val darkMode: String,
    val language: String,
    val signOut: String,
    val routesLive: String,
    val communityPowered: String,
    val fetchingRoutes: String,
    val kolarDistrictRoutes: String,
    val notifyContacts: String,
    val todayJourney: String,
    val youAreSafe: String,
    val allNotifications: String,
    val delayAlerts: String,
    val breakdownAlerts: String,
    val safeReachAlerts: String,
    val appearance: String,
    val notifications: String,
    val about: String
)

val EnglishStrings = AppStrings(
    appName = "Vidya-Vahini",
    studentCommuteBuddy = "Student Commute Buddy",
    selectYourRoute = "SELECT YOUR ROUTE",
    enterMobile = "Enter your mobile number",
    sendOtp = "Send OTP",
    verifyOtp = "Verify OTP",
    pingButton = "Ping — Bus just passed my stop!",
    safeReach = "I've reached college safely!",
    reportBreakdown = "Report a Breakdown",
    livePosition = "LIVE POSITION",
    minutesToStop = "minutes to your stop",
    settings = "Settings",
    profile = "Profile",
    darkMode = "Dark Mode",
    language = "Language",
    signOut = "Sign Out",
    routesLive = "routes live",
    communityPowered = "Community-powered · Real-time",
    fetchingRoutes = "Fetching live routes...",
    kolarDistrictRoutes = "Kolar District Routes",
    notifyContacts = "NOTIFY CONTACTS",
    todayJourney = "TODAY'S JOURNEY",
    youAreSafe = "You're Safe! 🎉",
    allNotifications = "All Notifications",
    delayAlerts = "Delay Alerts",
    breakdownAlerts = "Breakdown Alerts",
    safeReachAlerts = "Safe-Reach Alerts",
    appearance = "APPEARANCE",
    notifications = "NOTIFICATIONS",
    about = "ABOUT"
)

val KannadaStrings = AppStrings(
    appName = "ವಿದ್ಯಾ-ವಾಹಿನಿ",
    studentCommuteBuddy = "ವಿದ್ಯಾರ್ಥಿ ಪ್ರಯಾಣ ಸಹಾಯಕ",
    selectYourRoute = "ನಿಮ್ಮ ಮಾರ್ಗ ಆಯ್ಕೆ ಮಾಡಿ",
    enterMobile = "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    sendOtp = "OTP ಕಳುಹಿಸಿ",
    verifyOtp = "OTP ಪರಿಶೀಲಿಸಿ",
    pingButton = "ಬಸ್ ನನ್ನ ನಿಲ್ದಾಣ ದಾಟಿತು!",
    safeReach = "ನಾನು ಸುರಕ್ಷಿತವಾಗಿ ತಲುಪಿದ್ದೇನೆ!",
    reportBreakdown = "ಬ್ರೇಕ್‌ಡೌನ್ ವರದಿ ಮಾಡಿ",
    livePosition = "ನೇರ ಸ್ಥಾನ",
    minutesToStop = "ನಿಮ್ಮ ನಿಲ್ದಾಣಕ್ಕೆ ನಿಮಿಷಗಳು",
    settings = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    profile = "ಪ್ರೊಫೈಲ್",
    darkMode = "ಡಾರ್ಕ್ ಮೋಡ್",
    language = "ಭಾಷೆ",
    signOut = "ಸೈನ್ ಔಟ್",
    routesLive = "ಮಾರ್ಗಗಳು ನೇರ",
    communityPowered = "ಸಮುದಾಯ-ಚಾಲಿತ · ನೇರ-ಸಮಯ",
    fetchingRoutes = "ನೇರ ಮಾರ್ಗಗಳನ್ನು ತರಲಾಗುತ್ತಿದೆ...",
    kolarDistrictRoutes = "ಕೋಲಾರ ಜಿಲ್ಲಾ ಮಾರ್ಗಗಳು",
    notifyContacts = "ಸಂಪರ್ಕಗಳಿಗೆ ತಿಳಿಸಿ",
    todayJourney = "ಇಂದಿನ ಪ್ರಯಾಣ",
    youAreSafe = "ನೀವು ಸುರಕ್ಷಿತರು! 🎉",
    allNotifications = "ಎಲ್ಲಾ ಅಧಿಸೂಚನೆಗಳು",
    delayAlerts = "ವಿಳಂಬ ಎಚ್ಚರಿಕೆಗಳು",
    breakdownAlerts = "ಬ್ರೇಕ್‌ಡೌನ್ ಎಚ್ಚರಿಕೆಗಳು",
    safeReachAlerts = "ಸೇಫ್-ರೀಚ್ ಎಚ್ಚರಿಕೆಗಳು",
    appearance = "ನೋಟ",
    notifications = "ಅಧಿಸೂಚನೆಗಳು",
    about = "ಬಗ್ಗೆ"
)

val HindiStrings = AppStrings(
    appName = "विद्या-वाहिनी",
    studentCommuteBuddy = "छात्र यात्रा सहायक",
    selectYourRoute = "अपना मार्ग चुनें",
    enterMobile = "अपना मोबाइल नंबर दर्ज करें",
    sendOtp = "OTP भेजें",
    verifyOtp = "OTP सत्यापित करें",
    pingButton = "बस मेरे स्टॉप से गुज़री!",
    safeReach = "मैं सुरक्षित पहुंच गया!",
    reportBreakdown = "ब्रेकडाउन रिपोर्ट करें",
    livePosition = "लाइव स्थिति",
    minutesToStop = "आपके स्टॉप तक मिनट",
    settings = "सेटिंग्स",
    profile = "प्रोफ़ाइल",
    darkMode = "डार्क मोड",
    language = "भाषा",
    signOut = "साइन आउट",
    routesLive = "मार्ग लाइव",
    communityPowered = "समुदाय-संचालित · रीयल-टाइम",
    fetchingRoutes = "लाइव मार्ग लाए जा रहे हैं...",
    kolarDistrictRoutes = "कोलार जिला मार्ग",
    notifyContacts = "संपर्कों को सूचित करें",
    todayJourney = "आज की यात्रा",
    youAreSafe = "आप सुरक्षित हैं! 🎉",
    allNotifications = "सभी सूचनाएं",
    delayAlerts = "देरी अलर्ट",
    breakdownAlerts = "ब्रेकडाउन अलर्ट",
    safeReachAlerts = "सेफ-रीच अलर्ट",
    appearance = "रूप",
    notifications = "सूचनाएं",
    about = "के बारे में"
)

val TeluguStrings = AppStrings(
    appName = "విద్యా-వాహిని",
    studentCommuteBuddy = "విద్యార్థి ప్రయాణ సహాయకుడు",
    selectYourRoute = "మీ మార్గాన్ని ఎంచుకోండి",
    enterMobile = "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    sendOtp = "OTP పంపండి",
    verifyOtp = "OTP ధృవీకరించండి",
    pingButton = "బస్సు నా స్టాప్ దాటింది!",
    safeReach = "నేను సురక్షితంగా చేరుకున్నాను!",
    reportBreakdown = "బ్రేక్‌డౌన్ రిపోర్ట్ చేయండి",
    livePosition = "లైవ్ స్థానం",
    minutesToStop = "మీ స్టాప్‌కు నిమిషాలు",
    settings = "సెట్టింగులు",
    profile = "ప్రొఫైల్",
    darkMode = "డార్క్ మోడ్",
    language = "భాష",
    signOut = "సైన్ అవుట్",
    routesLive = "మార్గాలు లైవ్",
    communityPowered = "సమాజ-ఆధారిత · నిజ-సమయం",
    fetchingRoutes = "లైవ్ మార్గాలు తీసుకొస్తున్నాము...",
    kolarDistrictRoutes = "కోలార్ జిల్లా మార్గాలు",
    notifyContacts = "సంప్రదింపులకు తెలియజేయండి",
    todayJourney = "నేటి ప్రయాణం",
    youAreSafe = "మీరు సురక్షితంగా ఉన్నారు! 🎉",
    allNotifications = "అన్ని నోటిఫికేషన్లు",
    delayAlerts = "ఆలస్య హెచ్చరికలు",
    breakdownAlerts = "బ్రేక్‌డౌన్ హెచ్చరికలు",
    safeReachAlerts = "సేఫ్-రీచ్ హెచ్చరికలు",
    appearance = "రూపం",
    notifications = "నోటిఫికేషన్లు",
    about = "గురించి"
)

val LocalStrings = compositionLocalOf { EnglishStrings }

fun getStrings(language: String): AppStrings = when (language) {
    "ಕನ್ನಡ" -> KannadaStrings
    "हिंदी"  -> HindiStrings
    "తెలుగు" -> TeluguStrings
    else     -> EnglishStrings
}